In [1]:
%matplotlib widget
from bmcs_shell.api import WBTessellation, WBShellAnalysis, MATS2DElastic, FETriangularMesh, FETS2DMITC, MATSShellElastic, AbaqusLink 
import numpy as np

In [2]:
# tmodel = MATS2DElastic(E=28000, nu=0.2)
tmodel = MATSShellElastic(E=28000, nu=0.2)
n_phi_plus=2
n_x_plus=1
wbm = WBShellAnalysis(h=10, tmodel=tmodel)

In [3]:
data = dict(alpha=1.24, a=500, a_high=3000, b=900, b_high=3000, c=400, c_high=2000,
            n_phi_plus=n_phi_plus, n_x_plus=n_x_plus, show_nodes=False)
wbm.geo.trait_set(**data)

In [23]:
wbm.bcs._bc_fixed

array([[ 9.,  0.,  0.,  0., nan, nan],
       [ 8.,  0.,  0.,  0., nan, nan]])

In [5]:
wbm.run()

In [6]:
wbm.xdomain.Eia

AttributeError: 'TriXDomainMITC' object has no attribute 'Eia'

In [9]:
wbm.xdomain.F_N

array([[ 0,  1,  2],
       [ 4,  3,  0],
       [ 5,  1,  0],
       [ 0,  2,  6],
       [ 0,  3,  5],
       [ 6,  4,  0],
       [ 7,  3,  4],
       [ 9,  8,  7],
       [10,  3,  7],
       [ 7,  4, 11],
       [ 7,  8, 10],
       [11,  9,  7]])

In [10]:
wbm.xdomain.mesh.I_Fi

array([[ 0,  1,  2],
       [ 0,  3,  4],
       [ 0,  1,  5],
       [ 0,  2,  6],
       [ 0,  3,  5],
       [ 0,  4,  6],
       [ 7,  3,  4],
       [ 7,  8,  9],
       [ 7,  3, 10],
       [ 7,  4, 11],
       [ 7,  8, 10],
       [ 7,  9, 11]])

In [8]:
al._inp_boundary_conditions 

TypeError: can only concatenate str (not "numpy.float64") to str

In [5]:
al = AbaqusLink(shell_analysis=wbm, n_split=10)
al.model_name = 'test_name'
al.build_inp()

0
2
inp file test_name.inp written


In [4]:
wbm.interact()

analysis: setup_plot
analysis: U_I
w_m called!!
analysis: update_plot
analysis: U_I


C:\Users\spart\miniconda3\envs\bmcs_env\lib\site-packages\traittypes\traittypes.py:97: UserWarning: Given trait value dtype "float64" does not match required type "float32". A coerced copy has been created.
  warnings.warn(


In [4]:
max(wbm.hist.U_t[-1])

IndexError: index -1 is out of bounds for axis 0 with size 0

In [6]:
np.arange(60).reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [5]:
[print('dof: ' + str(b.dof) + ', value: ' + str(b.value)) for b in wbm.bc]

dof: 10, value: 0.0
dof: 11, value: 0.0
dof: 12, value: 0.0
dof: 5, value: 0.0
dof: 6, value: 0.0
dof: 7, value: 0.0
dof: 45, value: 0.0
dof: 46, value: 0.0
dof: 47, value: 0.0
dof: 40, value: 0.0
dof: 41, value: 0.0
dof: 42, value: 0.0
dof: 55, value: 0.0
dof: 56, value: 0.0
dof: 57, value: 0.0
dof: 50, value: 0.0
dof: 51, value: 0.0
dof: 52, value: 0.0
dof: 30, value: 0.0
dof: 31, value: 0.0
dof: 32, value: 0.0
dof: 25, value: 0.0
dof: 26, value: 0.0
dof: 27, value: 0.0
dof: 22, value: -20000.0
dof: 17, value: -20000.0


[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [6]:
xx_Ei, yy_Ei = np.einsum('...a->a...', wbm.xdomain.x_Eia)
yy_Ei[:, 1] - yy_Ei[:, 2]

array([-874.15724895, -900.00023524, -397.5538468 , -349.66320896,
       -349.66313046, -397.55382519, -874.15728924, -900.00005939,
       -397.55382519, -349.66313046, -349.66320896, -397.5538468 ])

In [12]:
wbm.xdomain.mesh.I_Fi

array([[ 0,  1,  2],
       [ 0,  3,  4],
       [ 0,  1,  5],
       [ 0,  2,  6],
       [ 0,  3,  5],
       [ 0,  4,  6],
       [ 7,  3,  4],
       [ 7,  8,  9],
       [ 7,  3, 10],
       [ 7,  4, 11],
       [ 7,  8, 10],
       [ 7,  9, 11]])

In [ ]:
bc_fixed = [BCDof(var= 'u', dof=dof, value=0) for dof in fixed_dofs]
bc_loaded = [BCDof(var= 'f', dof=dof, value=u_cntl) for dof in loaded_dofs]
ts = TStepBC(
    domains=[(xdomain, tmodel)],
    bc=bc_fixed + bc_loaded,
)

In [15]:
wbm.bc

array([], dtype=float64)

In [13]:
wbm.xdomain.mesh.X_Id

array([[    0.        ,   806.63830566,   -20.85449219],
       [  499.99996948,  1650.16491699,   292.93359375],
       [ -499.99996948,  1650.16491699,   292.93359375],
       [  499.99996948,     0.        ,   378.31347656],
       [ -499.99996948,     0.        ,   378.31347656],
       [  129.91851807,   826.18609619,   356.95410156],
       [ -129.91851807,   826.18609619,   356.95410156],
       [    0.        ,  -806.63830566,   -20.85449219],
       [  499.99996948, -1650.16491699,   292.93359375],
       [ -499.99996948, -1650.16491699,   292.93359375],
       [  129.91851807,  -826.18609619,   356.95410156],
       [ -129.91851807,  -826.18609619,   356.95410156]])

In [18]:
X_Fid = wbm.xdomain.mesh.X_Id[wbm.xdomain.mesh.I_Fi]
X_Fid

array([[[    0.        ,   806.63830566,   -20.85449219],
        [  499.99996948,  1650.16491699,   292.93359375],
        [ -499.99996948,  1650.16491699,   292.93359375]],

       [[    0.        ,   806.63830566,   -20.85449219],
        [  499.99996948,     0.        ,   378.31347656],
        [ -499.99996948,     0.        ,   378.31347656]],

       [[    0.        ,   806.63830566,   -20.85449219],
        [  499.99996948,  1650.16491699,   292.93359375],
        [  129.91851807,   826.18609619,   356.95410156]],

       [[    0.        ,   806.63830566,   -20.85449219],
        [ -499.99996948,  1650.16491699,   292.93359375],
        [ -129.91851807,   826.18609619,   356.95410156]],

       [[    0.        ,   806.63830566,   -20.85449219],
        [  499.99996948,     0.        ,   378.31347656],
        [  129.91851807,   826.18609619,   356.95410156]],

       [[    0.        ,   806.63830566,   -20.85449219],
        [ -499.99996948,     0.        ,   378.31347656],
    

In [26]:
wbm.xdomain.Fa_normals[0]

array([[      0.        , -313788.0667854 ,  843526.55984335]])

In [21]:
wbm.xdomain.mesh.X_Id[wbm.xdomain.mesh.I_Fi][0][0]

array([  0.        , 806.63830566, -20.85449219])

## Understanding bc

In [8]:
xdomain = wbm.xdomain

In [9]:
fixed_xyz_nodes = xdomain.bc_J_xyz
fixed_xyz_nodes

array([2, 1, 9, 8])

In [10]:
xdomain.I_CDij

array([[[[ 2,  1],
         [ 6,  5],
         [ 4,  3]]],


       [[[ 9,  8],
         [13, 12],
         [11, 10]]]])

In [11]:
fixed_x_nodes = xdomain.bc_J_x
fixed_x_nodes

array([ 2,  6,  4,  4, 11,  9,  1,  5,  3,  3, 10,  8])

In [12]:
np.hstack([fixed_xyz_nodes, fixed_x_nodes])

array([ 2,  1,  9,  8,  2,  6,  4,  4, 11,  9,  1,  5,  3,  3, 10,  8])

In [13]:
fixed_nodes = np.unique(np.hstack([fixed_xyz_nodes, fixed_x_nodes]))
fixed_nodes

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11])

In [15]:
fixed_xyz_nodes = xdomain.bc_J_xyz
fixed_x_nodes = xdomain.bc_J_x
fixed_nodes = np.unique(np.hstack([fixed_xyz_nodes, fixed_x_nodes]))
fixed_xyz_dofs = (fixed_xyz_nodes[:, np.newaxis] * 3 + np.arange(3)[np.newaxis, :]).flatten()
fixed_x_dofs = (fixed_x_nodes[:, np.newaxis] * 3).flatten()
fixed_dofs = np.unique(np.hstack([fixed_xyz_dofs, fixed_x_dofs]))



In [6]:
xmodel = wbm.fe_domain[0].xmodel
xmodel.mesh.I_CDij

array([[[[23, 22],
         [27, 26],
         [25, 24]],

        [[51, 50],
         [55, 54],
         [53, 52]]],


       [[[30, 29],
         [34, 33],
         [32, 31]],

        [[58, 57],
         [62, 61],
         [60, 59]]],


       [[[37, 36],
         [41, 40],
         [39, 38]],

        [[65, 64],
         [69, 68],
         [67, 66]]],


       [[[44, 43],
         [48, 47],
         [46, 45]],

        [[72, 71],
         [76, 75],
         [74, 73]]]])

In [7]:
_, idx_remap = xmodel.mesh.unique_node_map

In [8]:
idx_remap[xmodel.mesh.I_CDij]

array([[[[19, 18],
         [21,  2],
         [20,  6]],

        [[34, 33],
         [ 1, 36],
         [ 5, 35]]],


       [[[20,  6],
         [24,  4],
         [23, 11]],

        [[ 5, 35],
         [ 3, 39],
         [10, 38]]],


       [[[23, 11],
         [27,  9],
         [26, 16]],

        [[10, 38],
         [ 8, 42],
         [15, 41]]],


       [[[26, 16],
         [31, 14],
         [30, 29]],

        [[15, 41],
         [13, 46],
         [45, 44]]]])

In [9]:
idx_remap[xmodel.mesh.I_CDij[(0, -1),:,(0, -1),:].flatten()]

array([19, 18, 34, 33, 30, 29, 45, 44])

In [10]:
xmodel

In [12]:
import numpy as np
alpha_range = np.linspace(0.5, 1.3, 10)
a_range = np.linspace(300,500,10)

In [15]:
tmodel = MATS2DElastic(E=28000, nu=0.2)
import numpy as np
U_grid = []
sig_grid = []
for alpha in alpha_range:
    U_list = []
    sig_list = []
    for a in a_range:
        wbm = WBShellAnalysis(F=-20000, h=10, tmodel=tmodel)
        data = dict(alpha=alpha, a=a, a_high=2000, b=1250, b_high=2000, c=400, c_high=2000,
                    n_phi_plus=n_phi_plus, n_x_plus=n_x_plus)
        wbm.wb_mesh.trait_set(**data)
        max_U = wbm.get_max_vals()
        
        U1 = wbm.hist.U_t[-1]
        eps1 = wbm.fe_domain[0].xmodel.map_U_to_field(U1)
        sig1, _ = wbm.fe_domain[0].tmodel.get_corr_pred(eps1,1)
        sig_x, sig_y, tau = sig1.T
        sig_ab = np.einsum('ab...->...ab', np.array([[sig_x, tau], [tau, sig_y]], dtype=np.float_))
        sig_val, sig_dir = np.linalg.eig(sig_ab)
        sig_list.append([np.min(sig_val), np.max(sig_val)])

        print(alpha, a, max_U)
        U_list.append(max_U)
    U_grid.append(U_list)
    sig_grid.append(sig_list)

RuntimeError: Factor is exactly singular

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
fig = plt.figure()
ax = fig.gca(projection='3d')
X, Y = np.meshgrid(alpha_range, a_range)
Z = np.array(U_grid)
surf = ax.plot_surface(X, Y, Z, 
                       color='green',
                       #linewidth=0, antialiased=False)
                    alpha=.0, linewidth=5,
                       #cmap=cm.gist_earth,antialiased=False, 
                shade=False,rstride=1, cstride=1)
Z = np.array(sig_grid)[:,:,1]
surf = ax.plot_surface(X, Y, Z,color='red', 
                       #cmap=cm.copper,
                    alpha=.3, linewidth=3,
                       #cmap=cm.gist_earth,antialiased=False, 
                shade=False,rstride=1, cstride=1)
Z = -np.array(sig_grid)[:,:,0]
surf = ax.plot_surface(X, Y, Z,color='blue', 
                       #cmap=cm.copper,
                    alpha=.6, linewidth=3,
                       #cmap=cm.gist_earth,antialiased=False, 
                shade=False,rstride=1, cstride=1)
ax.set_xlabel(r'$\alpha~[\mathrm{rad}]$')
ax.set_ylabel(r'$a~[\mathrm{mm}]$')
ax.set_zlabel(r'max compression [MPa]')


In [ ]:
i_alpha, i_a = 0, -1
wbm = WBShellAnalysis(F=-1000, tmodel=tmodel)
print('alpha', alpha_range[i_alpha],'a', a_range[i_a] )
data = dict(alpha=alpha_range[i_alpha], 
            a=a_range[i_a], a_high=2000, b=1250, b_high=2000, c=400, c_high=2000,
            n_phi_plus=n_phi_plus, n_x_plus=n_x_plus)
wbm.wb_mesh.trait_set(**data)
wbm.wb_mesh.interact()

In [ ]:
15000 / 39000 