# Waterbomb shell folder and designer

In [1]:
%matplotlib widget

In [2]:
import sympy as sp
sp.init_printing()
import numpy as np
import matplotlib.pylab as plt
import bmcs_utils.api as bu

In [3]:
from bmcs_shell.folding.waterbomb_cell import WBElem
from bmcs_shell.folding.waterbomb_shell import WBShell

In [4]:
data = dict(alpha=1, a=5, b=9, c=4, n_phi_plus=2, n_x_plus=2)

In [7]:
wb = WBElem(**data)
ws = WBShell(wb_cell=wb,**data) 

In [8]:
bu.InteractiveWindow([ws,wb]).interact()

Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, background_color=16777215, camera=[2, -3, 0.2, 0.0, 0…

## Sketch of the applied generation method / concept

Sketch the discretization into the cells the cell midpoints 
cover a cylindric surface as a structured grid. 

Midpoints are arranged at the surface of the derived cylinder
parameters which depend on the folding angle $\alpha$ and $a, b, c$
parameters of the waterbomd cell. Then, a reference cell 
in an intermediate state of folding is broadcasted 
to the prepared grid of midpoints on the cylinders. 

In [7]:
n_phi_plus = 2
delta_phi = 0.3
phi_range = np.arange(-(n_phi_plus-1), n_phi_plus) * delta_phi
r_0 = -10

In [8]:
phi_range

array([-0.3,  0. ,  0.3])

In [9]:
X_phi_range = np.array([np.fabs(r_0) * np.sin(phi_range),
                 np.fabs(r_0) * np.cos(phi_range) + r_0]).T

In [96]:
fix, ax = plt.subplots(1,1)
ax.plot(*X_phi_range.T);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [97]:
n_x_plus = 2
delta_x = 0.5
X_x_range = np.arange(-(n_x_plus-1), n_x_plus) * delta_x
X_x_range

array([-0.5,  0. ,  0.5])

In [98]:
X_x_range[:, np.newaxis, np.newaxis]

array([[[-0.5]],

       [[ 0. ]],

       [[ 0.5]]])

In [99]:
X_phi_range[np.newaxis,:,:]

array([[[-2.95520207, -0.44663511],
        [ 0.        ,  0.        ],
        [ 2.95520207, -0.44663511]]])

In [100]:
n_idx_x = len(X_x_range)
n_idx_phi = len(X_phi_range)
idx_x = np.arange(n_idx_x)
idx_phi = np.arange(n_idx_phi)
idx_phi

array([0, 1, 2])

In [101]:
1+1 % 2

In [102]:
idx_x_ic = idx_x[(n_idx_x)%2::2]
idx_x_id = idx_x[(n_idx_x+1)%2::2]
idx_phi_ic = idx_phi[(n_idx_phi)%2::2]
idx_phi_id = idx_phi[(n_idx_phi+1)%2::2]

idx_x_ic, idx_phi_ic, idx_x_id, idx_phi_id

(array([1]), array([1]), array([0, 2]), array([0, 2]))

In [103]:
idx_map_ic = np.meshgrid(idx_x_ic, idx_phi_ic)
idx_map_id = np.meshgrid(idx_x_id, idx_phi_id)

In [104]:
idx_map_ic

[array([[1]]), array([[1]])]

In [105]:
X_C_a = np.c_[ X_x_range[idx_map_ic[0]].reshape(-1,1), X_phi_range[idx_map_ic[1]].reshape(-1,2) ]
X_D_a = np.c_[ X_x_range[idx_map_id[0]].reshape(-1,1), X_phi_range[idx_map_id[1]].reshape(-1,2) ]

In [106]:
X_C_a

array([[0., 0., 0.]])

In [107]:
X_D_a

array([[-0.5       , -2.95520207, -0.44663511],
       [ 0.5       , -2.95520207, -0.44663511],
       [-0.5       ,  2.95520207, -0.44663511],
       [ 0.5       ,  2.95520207, -0.44663511]])

In [108]:
from bmcs_shell.folding.waterbomb_shell import WBShell

In [79]:
WBShell().interact()

Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, background_color=16777215, camera=[2, -3, 0.2, 0.0, 0…